import { Montserrat } from "next/font/google";
import Nav from "@/components/Nav/Nav";
import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "GRATIA OF-GAD",
  description: "Generated by create next app",
};
const font = Montserrat({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={font.className}>
        <Nav />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
